version: "3.9"
services:
  cook_book:
    build: .
    command: >
      sh -c "
        cd app &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py loaddata name ingredients &&
        sleep 5 &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cookbook_db
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django

