version: '3.7'

services:

  # The application
  app:
    build:
      context: .
    image: &app app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - .env.dev
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    links:
      - db
    depends_on:
      - db

  # Database
  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=app_db