# Generated by Django 4.0.2 on 2022-02-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_alter_recipes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={},
        ),
    ]
